### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by calebpaine** [coreyramirezgomez/Brother-Printers-Zabbix-Template#3]
Getting the following error on import of the brother-printers-zabbix-template.xml template into Zabbix 3.0.1

`Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/graph_prototypes/graph_prototype(1)/ymin_item_1": unexpected tag "host".`

**Comment by girishkg** [comment]
Same here:
-------------------------------

Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(2)/graph_prototypes/graph_prototype(1)/ymax_item_1": unexpected tag "host".

-------------------------------
